spring:
  datasource:
    url: jdbc:mysql://162.14.122.80:3306/store_inventory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: store_inventory
    password: Xzcpc@2026
    hikari:
      maximum-pool-size: 30
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      keepalive-time: 60000
      connection-test-query: SELECT 1

logging:
  level:
    com.xzcpc: DEBUG
