server:
  port: 30261
  servlet:
    context-path: /storeInventory

spring:
  profiles:
    active: prod   # dev=本地Mock | prod=生产环境
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  upload:
    path: ./upload
  public-url: https://www.xzcpc-9pd.top/storeInventory

store:
  api:
    url: http://119.45.162.160:5174/api/publish/entities/mendianxinxi/records

material:
  api:
    url: http://119.45.162.160:5174/api/publish/entities/yuancailiao/records

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

wx:
  miniapp:
    appid: wx3081dfa30167bb6e
    msg-data-format: JSON

mp:
  jwt:
    expire-hours: 168
