CREATE TABLE IF NOT EXISTS employee (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  employee_id VARCHAR(32) NOT NULL COMMENT '员工业务ID',
  name VARCHAR(64) NOT NULL COMMENT '姓名',
  mobile VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  gender VARCHAR(16) DEFAULT NULL COMMENT '性别',
  birthday DATE DEFAULT NULL COMMENT '出生日期',
  store_id VARCHAR(32) NOT NULL COMMENT '门店ID',
  store_miniapp_no VARCHAR(64) DEFAULT NULL COMMENT '门店小程序号',
  store_name VARCHAR(128) NOT NULL COMMENT '门店名称快照',
  role VARCHAR(64) NOT NULL COMMENT '岗位',
  employment_type VARCHAR(32) DEFAULT NULL COMMENT '用工类型',
  entry_date DATE NOT NULL COMMENT '入职日期',
  leave_date DATE DEFAULT NULL COMMENT '离职日期',
  status VARCHAR(20) NOT NULL DEFAULT '在职' COMMENT '状态：在职/离职',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  UNIQUE KEY uk_employee_id (employee_id),
  KEY idx_employee_store (store_id),
  KEY idx_employee_store_miniapp_no (store_miniapp_no),
  KEY idx_employee_role (role),
  KEY idx_employee_status (status),
  KEY idx_employee_entry_date (entry_date),
  KEY idx_employee_del_flag (del_flag)
) COMMENT='员工表';
