-- ==============================================================================================
-- 【事故恢复】补回被误删的成本卡 RAW/SEMI 配方行
-- 生成时间：2026-09-11 13:11:58
--
-- 【事故原因】migration-cost-card-pack-20260911.sql 的 2) DELETE 段 AND/OR 优先级写错：
--     WHERE i.item_type = 'PACK'
--       AND p.product_name IN (第1组)
--        OR p.product_name IN (第2组) ...
--   MySQL 的 AND 优先级高于 OR，实际语义 = (item_type='PACK' AND 第1组) OR 第2组 OR …
--   ⇒ 第 2~7 组产品不受 item_type 约束，其 **RAW/SEMI 行被一并删除**。
--   第 1 组的 4 个产品（厚牛油果酸奶巴旦木(奶昔)/双倍牛油果蔓越莓/山野滇红(加雪顶)/
--   山野滇红(去雪顶)）共 7 张卡因 AND 生效而幸免。
--   （主脚本已修正为 WHERE i.item_type='PACK' AND ( … )，见其 2) 段注释）
--
-- 【损失范围】54 张卡、297 行 RAW/SEMI 配方行（PACK 行未受损，勿动）
-- 【恢复源】database/migration-cost-card-import-20260909.sql（原始导入脚本）
--   已核对：现存 259 行非 PACK 行与 import 脚本**逐行一致**（数量/单位/sort_no 全同），
--   故 import 是忠实恢复源，可原样回放。
--
-- 【安全性】
--   · 每条 INSERT 自带 `FROM cost_card WHERE card_name_full = '...'`，按卡名定位，不依赖 id
--   · 开头先删这 54 张卡的非 PACK 行 → 可重复执行不产生重复行
--   · 完全不触碰 PACK 行（包材明细保持 migration-cost-card-pack 已跑完的结果）
--
-- 【执行】1) 跑核对 A → 2) 跑 1) 删除 → 3) 跑 2) 回放 → 4) 跑核对 B
-- ==============================================================================================

SET NAMES utf8mb4;

-- ---------- 核对 A：执行前（期望 before_rows = 0） ----------
-- SELECT COUNT(*) AS before_rows FROM cost_card_item i
-- JOIN cost_card k ON k.id = i.card_id
-- WHERE i.item_type <> 'PACK' AND k.card_name_full IN (
--   '手作米布鲜奶茶(冰)', '手作米布鲜奶茶(去冰/常温)',
--   '手作米布鲜奶茶(少冰)', '手作米布鲜奶茶(热)',
--   '手炒黑糖珍珠(去冰/常温)', '手炒黑糖珍珠(少冰)',
--   '手炒黑糖珍珠(正常冰)', '手炒黑糖珍珠(热)',
--   '新10月黄油红糖(等普洱)正常冰', '新10月黄油红糖(等普洱)温热',
--   '杨枝甘露双倍果肉常温', '杨枝甘露双倍果肉正常冰',
--   '树番茄舂柠檬少冰', '树番茄舂柠檬少少冰',
--   '树番茄舂柠檬正常冰', '树番茄话梅·德宏少冰',
--   '树番茄话梅·德宏正常冰', '清甜芭乐冰茶',
--   '清甜芭乐冰茶少冰', '清甜芭乐果奶',
--   '清甜芭乐果奶少冰', '滇橄榄舂柠檬少冰',
--   '滇橄榄舂柠檬少少冰', '滇橄榄舂柠檬正常冰',
--   '滇红舂柠檬少冰', '滇红舂柠檬少少冰',
--   '滇红舂柠檬正常冰', '牛油果燕麦椰椰',
--   '牛油果碧根果', '牛油果酸奶巴旦木',
--   '玫瑰奶白酒-冰', '玫瑰奶白酒-热(无糖版)',
--   '纸杯白毫茉莉(少冰)', '纸杯白毫茉莉(正常冰)',
--   '纸杯白毫茉莉(温热)', '茉莉奶白常温/去冰',
--   '茉莉奶白正常冰', '茉莉奶白温热',
--   '茉莉舂柠檬少冰', '茉莉舂柠檬少少冰',
--   '茉莉舂柠檬正常冰', '酸奶紫米露',
--   '酸角话梅·版纳少冰', '酸角话梅·版纳正常冰',
--   '青柚与葡萄柚', '青柚与葡萄柚(少冰)',
--   '青柚乌龙冰茶', '青柚乌龙冰茶(少冰)',
--   '青柚滇橄榄少冰', '青柚滇橄榄正常冰',
--   '鲜奶黑糖啵啵(少冰)', '鲜奶黑糖啵啵(常温)',
--   '鲜奶黑糖啵啵(正常冰)', '鲜奶黑糖啵啵(温热)'
-- );

-- ---------- 1) 清掉这 54 张卡的非 PACK 行（当前为 0；重复执行时兜底） ----------
DELETE i FROM cost_card_item i
JOIN cost_card k ON k.id = i.card_id
WHERE i.item_type <> 'PACK' AND k.card_name_full IN (
  '手作米布鲜奶茶(冰)', '手作米布鲜奶茶(去冰/常温)',
  '手作米布鲜奶茶(少冰)', '手作米布鲜奶茶(热)',
  '手炒黑糖珍珠(去冰/常温)', '手炒黑糖珍珠(少冰)',
  '手炒黑糖珍珠(正常冰)', '手炒黑糖珍珠(热)',
  '新10月黄油红糖(等普洱)正常冰', '新10月黄油红糖(等普洱)温热',
  '杨枝甘露双倍果肉常温', '杨枝甘露双倍果肉正常冰',
  '树番茄舂柠檬少冰', '树番茄舂柠檬少少冰',
  '树番茄舂柠檬正常冰', '树番茄话梅·德宏少冰',
  '树番茄话梅·德宏正常冰', '清甜芭乐冰茶',
  '清甜芭乐冰茶少冰', '清甜芭乐果奶',
  '清甜芭乐果奶少冰', '滇橄榄舂柠檬少冰',
  '滇橄榄舂柠檬少少冰', '滇橄榄舂柠檬正常冰',
  '滇红舂柠檬少冰', '滇红舂柠檬少少冰',
  '滇红舂柠檬正常冰', '牛油果燕麦椰椰',
  '牛油果碧根果', '牛油果酸奶巴旦木',
  '玫瑰奶白酒-冰', '玫瑰奶白酒-热(无糖版)',
  '纸杯白毫茉莉(少冰)', '纸杯白毫茉莉(正常冰)',
  '纸杯白毫茉莉(温热)', '茉莉奶白常温/去冰',
  '茉莉奶白正常冰', '茉莉奶白温热',
  '茉莉舂柠檬少冰', '茉莉舂柠檬少少冰',
  '茉莉舂柠檬正常冰', '酸奶紫米露',
  '酸角话梅·版纳少冰', '酸角话梅·版纳正常冰',
  '青柚与葡萄柚', '青柚与葡萄柚(少冰)',
  '青柚乌龙冰茶', '青柚乌龙冰茶(少冰)',
  '青柚滇橄榄少冰', '青柚滇橄榄正常冰',
  '鲜奶黑糖啵啵(少冰)', '鲜奶黑糖啵啵(常温)',
  '鲜奶黑糖啵啵(正常冰)', '鲜奶黑糖啵啵(温热)'
);

-- ---------- 2) 从原始导入脚本回放 297 行 RAW/SEMI ----------
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '米布（g）', '冷冻牛奶米布', 'cmpdj8ksx01t43pmiwc297n9j', 'WP0354', NULL, 90.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 1 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 35.0, 'ml', 0.0225, 0.7875, 2 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 40.0, 'ml', 0.016, 0.64, 3 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 120.0, 'ml', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 5 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '米布（g）', '冷冻牛奶米布', 'cmpdj8ksx01t43pmiwc297n9j', 'WP0354', NULL, 90.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 1 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 40.0, 'ml', 0.0225, 0.9, 2 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 45.0, 'ml', 0.016, 0.72, 3 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 140.0, 'ml', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 5 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '米布（g）', '冷冻牛奶米布', 'cmpdj8ksx01t43pmiwc297n9j', 'WP0354', NULL, 90.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 1 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 45.0, 'ml', 0.0225, 1.0125, 2 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 60.0, 'ml', 0.016, 0.96, 3 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 170.0, 'ml', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 15.0, 'g', 0.0415, 0.6225, 5 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '米布（g）', '冷冻牛奶米布', 'cmpdj8ksx01t43pmiwc297n9j', 'WP0354', NULL, 90.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 1 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 50.0, 'ml', 0.0225, 1.125, 2 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 60.0, 'ml', 0.016, 0.96, 3 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 180.0, 'ml', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 5 FROM cost_card WHERE card_name_full = '手作米布鲜奶茶(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 0 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 15.0, 'g', 0.01533333, 0.23, 1 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 2 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '咸法干酪', '咸法干酪乳', 'cmpdj8isx012l3pmi1rwagefc', 'WP0642', NULL, 10.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 25.0, 'g', 0.0225, 0.5625, 4 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 100.0, 'ml', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 0 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 15.0, 'g', 0.01533333, 0.23, 1 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 2 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '咸法干酪', '咸法干酪乳', 'cmpdj8isx012l3pmi1rwagefc', 'WP0642', NULL, 10.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 30.0, 'g', 0.0225, 0.675, 4 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 120.0, 'ml', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 0 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 15.0, 'g', 0.01533333, 0.23, 1 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 15.0, 'g', 0.0415, 0.6225, 2 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 170.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 45.0, 'g', 0.0225, 1.0125, 4 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 60.0, 'g', 0.016, 0.96, 5 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(去冰/常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 0 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.00766667, 0.23, 1 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 2 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '山野滇红（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 180.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 50.0, 'g', 0.0225, 1.125, 4 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 60.0, 'g', 0.016, 0.96, 5 FROM cost_card WHERE card_name_full = '手炒黑糖珍珠(热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 15.0, 'g', 0.0176, 0.264, 0 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 20.0, 'ml', 0.0225, 0.45, 1 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '咸法干酪（ml)', '咸法干酪乳', 'cmpdj8isx012l3pmi1rwagefc', 'WP0642', NULL, 20.0, 'ml', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '普洱', '普洱茶茶汤', NULL, NULL, 'WP0557', 220.0, 'g', 0.003824, 0.8413, 3 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黄油红糖', '黄油红糖', NULL, NULL, 'WP0537', 50.0, 'g', 0.039563, 1.9782, 4 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '淡奶油（ml)', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'ml', 0.0415, 0.415, 5 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 15.0, 'g', 0.0176, 0.264, 0 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 20.0, 'ml', 0.0225, 0.45, 1 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '咸法干酪（ml)', '咸法干酪乳', 'cmpdj8isx012l3pmi1rwagefc', 'WP0642', NULL, 20.0, 'ml', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '普洱', '普洱茶茶汤', NULL, NULL, 'WP0557', 280.0, 'g', 0.003824, 1.0707, 3 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黄油红糖', '黄油红糖', NULL, NULL, 'WP0537', 45.0, 'g', 0.039563, 1.7803, 4 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 5 FROM cost_card WHERE card_name_full = '新10月黄油红糖(等普洱)温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 10.0, 'g', 0.0176, 0.176, 0 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '芒果预制', '芒果预制', NULL, NULL, NULL, 140.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '芒果粒', '芒果粒', NULL, NULL, 'WP0689', 30.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '白柚', '白柚', NULL, NULL, NULL, 10.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '小丸子', '小丸子', NULL, NULL, 'WP0574', 30.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '调制椰乳', '调制椰奶', NULL, NULL, 'WP0688', 40.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 15.0, 'g', 0.0176, 0.264, 0 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉常温';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '芒果预制', '芒果预制', NULL, NULL, NULL, 160.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉常温';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '芒果粒', '芒果粒', NULL, NULL, 'WP0689', 30.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉常温';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '白柚', '白柚', NULL, NULL, NULL, 10.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉常温';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '小丸子', '小丸子', NULL, NULL, 'WP0574', 30.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉常温';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '调制椰乳', '调制椰奶', NULL, NULL, 'WP0688', 40.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '杨枝甘露双倍果肉常温';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '树番茄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 45.0, 'g', 0.0176, 0.792, 1 FROM cost_card WHERE card_name_full = '树番茄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '树番茄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '树番茄浆', '冷冻树番茄', 'cmpdj8ksi01sz3pmicehinp5h', 'WP0356', NULL, 40.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '树番茄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 140.0, 'ml', 0.003824, 0.5354, 4 FROM cost_card WHERE card_name_full = '树番茄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 10.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '树番茄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 50.0, 'g', 0.0176, 0.88, 1 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '树番茄浆', '冷冻树番茄', 'cmpdj8ksi01sz3pmicehinp5h', 'WP0356', NULL, 50.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 170.0, 'ml', 0.003824, 0.6501, 4 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 10.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 50.0, 'g', 0.017552, 0.8776, 0 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 45.0, 'g', 0.0176, 0.792, 1 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '树番茄浆', '冷冻树番茄', 'cmpdj8ksi01sz3pmicehinp5h', 'WP0356', NULL, 40.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '兰韵茶汤', '兰韵清露茶汤', NULL, NULL, 'WP0552', 180.0, 'g', 0.004364, 0.7855, 4 FROM cost_card WHERE card_name_full = '树番茄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 1 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅饮料浓浆', '话梅饮料浓浆', 'cmpdj8hyy00rr3pmicts05mxa', 'WP0850', NULL, 10.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 3 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 3.0, 'g', 0.04333333, 0.13, 4 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '树番茄浆', '冷冻树番茄', 'cmpdj8ksi01sz3pmicehinp5h', 'WP0356', NULL, 30.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '滇红茶汤', '金芽滇红茶汤', NULL, NULL, 'WP0556', 150.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 35.0, 'g', 0.0176, 0.616, 1 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅饮料浓浆', '话梅饮料浓浆', 'cmpdj8hyy00rr3pmicts05mxa', 'WP0850', NULL, 10.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 3 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 3.0, 'g', 0.04333333, 0.13, 4 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '树番茄浆', '冷冻树番茄', 'cmpdj8ksi01sz3pmicehinp5h', 'WP0356', NULL, 30.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '滇红茶汤', '金芽滇红茶汤', NULL, NULL, 'WP0556', 150.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '树番茄话梅·德宏少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制芭乐浆', '预制芭乐汁', NULL, NULL, 'WP0857', 100.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬', '柠檬片', NULL, NULL, 'WP0534', 30.0, 'g', 0.017552, 0.5266, 1 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 20.0, 'g', 0.0176, 0.352, 2 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（ml）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'ml', 0.025, 0.125, 3 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶汤', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 140.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 15.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制南姜', '预制南姜汁', NULL, NULL, 'WP0888', 5.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 3.0, 'g', 0.04333333, 0.13, 7 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制芭乐浆', '预制芭乐汁', NULL, NULL, 'WP0857', 110.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬', '柠檬片', NULL, NULL, 'WP0534', 30.0, 'g', 0.017552, 0.5266, 1 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 2 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（ml）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'ml', 0.025, 0.125, 3 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶汤', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 140.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 20.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制南姜', '预制南姜汁', NULL, NULL, 'WP0888', 5.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 3.0, 'g', 0.04333333, 0.13, 7 FROM cost_card WHERE card_name_full = '清甜芭乐冰茶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制芭乐浆', '预制芭乐汁', NULL, NULL, 'WP0857', 75.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '清甜芭乐果奶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 1 FROM cost_card WHERE card_name_full = '清甜芭乐果奶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶汤', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 160.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '清甜芭乐果奶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 30.0, 'ml', 0.0225, 0.675, 3 FROM cost_card WHERE card_name_full = '清甜芭乐果奶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 4 FROM cost_card WHERE card_name_full = '清甜芭乐果奶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制芭乐浆', '预制芭乐汁', NULL, NULL, 'WP0857', 80.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '清甜芭乐果奶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 1 FROM cost_card WHERE card_name_full = '清甜芭乐果奶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶汤', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 180.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '清甜芭乐果奶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 35.0, 'ml', 0.0225, 0.7875, 3 FROM cost_card WHERE card_name_full = '清甜芭乐果奶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 4 FROM cost_card WHERE card_name_full = '清甜芭乐果奶少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄汁（ml）', '橄榄混合汁', NULL, NULL, 'WP0758', 50.0, 'ml', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 20.0, 'g', 0.017552, 0.351, 1 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 35.0, 'g', 0.0176, 0.616, 2 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（ml）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 15.0, 'ml', 0.025, 0.375, 3 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 85.0, 'ml', 0.003824, 0.325, 4 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄汁（ml）', '橄榄混合汁', NULL, NULL, 'WP0758', 55.0, 'ml', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 20.0, 'g', 0.017552, 0.351, 1 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 40.0, 'g', 0.0176, 0.704, 2 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（ml）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 15.0, 'ml', 0.025, 0.375, 3 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 90.0, 'ml', 0.003824, 0.3442, 4 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄汁（ml）', '橄榄混合汁', NULL, NULL, 'WP0758', 80.0, 'ml', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 20.0, 'g', 0.017552, 0.351, 1 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 60.0, 'g', 0.0176, 1.056, 2 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（ml）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 10.0, 'ml', 0.025, 0.25, 3 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '兰韵观音（ml）', '兰韵清露茶汤', NULL, NULL, 'WP0552', 140.0, 'ml', 0.004364, 0.611, 4 FROM cost_card WHERE card_name_full = '滇橄榄舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '滇红舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 50.0, 'g', 0.0176, 0.88, 1 FROM cost_card WHERE card_name_full = '滇红舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '滇红舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '滇红茶（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 150.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '滇红舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '滇红舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 55.0, 'g', 0.0176, 0.968, 1 FROM cost_card WHERE card_name_full = '滇红舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '滇红舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '滇红茶（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 160.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '滇红舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '滇红舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 60.0, 'g', 0.0176, 1.056, 1 FROM cost_card WHERE card_name_full = '滇红舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '滇红舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '滇红茶（ml）', '金芽滇红茶汤', NULL, NULL, 'WP0556', 180.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '滇红舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '新鲜牛油果（g）', '新鲜牛油果', NULL, NULL, 'WP0641', 30.0, 'g', 0.050091, 1.5027, 0 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '燕麦龙珠（g）', '燕麦龙珠（半成品）', NULL, NULL, 'WP0648', 20.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '奇亚籽（ml）', '奇亚籽（半成品）', NULL, NULL, 'WP0643', 30.0, 'ml', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '牛油果泥（g）', '牛油果泥', NULL, NULL, 'WP0531', 35.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 4 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '羽衣甘蓝叶（g)', '羽衣甘蓝叶（半成品）', NULL, NULL, 'WP0549', 7.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 40.0, 'ml', 0.0225, 0.9, 6 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '厚椰乳（ml）', '厚椰乳', 'cmpdj8itd012q3pmih1bdgb13', 'WP0639', NULL, 60.0, 'ml', NULL, NULL, 7 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '大麦若叶粉', '大麦若叶粉', 'cmpdj8kpj01sa3pmih7xe7b0b', 'WP0363', NULL, 0.8, 'g', NULL, NULL, 8 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '乍甸酸奶（g)', '乍甸酸奶', 'cmpdj8kl201qr3pmix7x4o40w', 'WP0383', NULL, 2.6, 'g', NULL, NULL, 9 FROM cost_card WHERE card_name_full = '牛油果燕麦椰椰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '碧根果（g）', '碧根果仁', 'cmpdj8kqf01sk3pmi89jldgb5', 'WP0361', NULL, 8.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '牛油果碧根果';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 40.0, 'ml', 0.0225, 0.9, 1 FROM cost_card WHERE card_name_full = '牛油果碧根果';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '干酪（g)', '干酪', NULL, NULL, 'WP0596', 20.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '牛油果碧根果';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 3 FROM cost_card WHERE card_name_full = '牛油果碧根果';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '羽衣甘蓝叶（g)', '羽衣甘蓝叶（半成品）', NULL, NULL, 'WP0549', 8.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '牛油果碧根果';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '牛油果泥（g）', '牛油果泥', NULL, NULL, 'WP0531', 50.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '牛油果碧根果';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '巴旦木（g）', '剥壳巴旦木1公斤', 'cmpdj8koz01s53pmidkhb5vp9', 'WP0364', NULL, 13.0, 'g', 0.08, 1.04, 0 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 40.0, 'ml', 0.0225, 0.9, 1 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '调制椰奶', '调制椰奶', NULL, NULL, 'WP0688', 15.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '酸奶（g)', '乍甸酸奶', 'cmpdj8kl201qr3pmix7x4o40w', 'WP0383', NULL, 30.0, 'g', 0.01366667, 0.41, 3 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.01133333, 0.34, 4 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '羽衣甘蓝（g)', '羽衣甘蓝汁', NULL, NULL, 'WP0538', 3.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '牛油果泥（g）', '牛油果泥', NULL, NULL, 'WP0531', 50.0, 'g', NULL, NULL, 6 FROM cost_card WHERE card_name_full = '牛油果酸奶巴旦木';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '玫瑰饮料浓浆', '玫瑰饮料浓浆', 'cmpdoxkg3yj33wsegydvd38s', 'WP0922', NULL, 30.0, 'g', 0.04, 1.2, 0 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 40.0, 'g', 0.0225, 0.9, 1 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '悦鲜活鲜奶', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 60.0, 'g', 0.00183333, 0.11, 2 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 60.0, 'ml', 0.003824, 0.2294, 3 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '米酒', '甜白酒', 'cmqiwh3i006hj3pq38gpn0npw', 'WP0917', NULL, 70.0, 'g', 0.015, 1.05, 4 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '玫瑰花', '花瓣（原材料）', 'cmq28fd2l04g53pq3harnjxz2', 'WP0583', NULL, 0.02, 'g', 1.0, 0.02, 5 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '小丸子', '小丸子', NULL, NULL, 'WP0574', 40.0, 'g', 0.0113, 0.452, 6 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '玫瑰饮料浓浆', '玫瑰饮料浓浆', 'cmpdoxkg3yj33wsegydvd38s', 'WP0922', NULL, 30.0, 'g', 0.04, 1.2, 0 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 45.0, 'g', 0.0225, 1.0125, 1 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '悦鲜活鲜奶', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 70.0, 'g', 0.00183333, 0.1283, 2 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 100.0, 'ml', 0.003824, 0.3824, 3 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '米酒', '甜白酒', 'cmqiwh3i006hj3pq38gpn0npw', 'WP0917', NULL, 80.0, 'g', 0.015, 1.2, 4 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '玫瑰花', '花瓣（原材料）', 'cmq28fd2l04g53pq3harnjxz2', 'WP0583', NULL, 0.02, 'g', 1.0, 0.02, 5 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '小丸子', '小丸子', NULL, NULL, 'WP0574', 50.0, 'g', 0.0133, 0.665, 6 FROM cost_card WHERE card_name_full = '玫瑰奶白酒-热(无糖版)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 0 FROM cost_card WHERE card_name_full = '纸杯白毫茉莉(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 180.0, 'ml', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '纸杯白毫茉莉(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 35.0, 'g', 0.0176, 0.616, 0 FROM cost_card WHERE card_name_full = '纸杯白毫茉莉(温热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 250.0, 'ml', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '纸杯白毫茉莉(温热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 0 FROM cost_card WHERE card_name_full = '纸杯白毫茉莉(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 200.0, 'ml', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '纸杯白毫茉莉(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 0 FROM cost_card WHERE card_name_full = '茉莉奶白正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml）', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 30.0, 'ml', 0.0225, 0.675, 1 FROM cost_card WHERE card_name_full = '茉莉奶白正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 40.0, 'ml', 0.016, 0.64, 2 FROM cost_card WHERE card_name_full = '茉莉奶白正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 180.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '茉莉奶白正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 35.0, 'g', 0.0176, 0.616, 0 FROM cost_card WHERE card_name_full = '茉莉奶白温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml）', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 50.0, 'ml', 0.0225, 1.125, 1 FROM cost_card WHERE card_name_full = '茉莉奶白温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 40.0, 'ml', 0.016, 0.64, 2 FROM cost_card WHERE card_name_full = '茉莉奶白温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 280.0, 'ml', 0.00478571, 1.34, 3 FROM cost_card WHERE card_name_full = '茉莉奶白温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 10.0, 'g', 0.0415, 0.415, 4 FROM cost_card WHERE card_name_full = '茉莉奶白温热';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 35.0, 'g', 0.0176, 0.616, 0 FROM cost_card WHERE card_name_full = '茉莉奶白常温/去冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml）', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 50.0, 'ml', 0.0225, 1.125, 1 FROM cost_card WHERE card_name_full = '茉莉奶白常温/去冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml)', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 40.0, 'ml', 0.016, 0.64, 2 FROM cost_card WHERE card_name_full = '茉莉奶白常温/去冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 280.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '茉莉奶白常温/去冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '茉莉舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 50.0, 'g', 0.0176, 0.88, 1 FROM cost_card WHERE card_name_full = '茉莉舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '茉莉舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶（ml）', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 150.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '茉莉舂柠檬正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 55.0, 'g', 0.0176, 0.968, 1 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶（ml）', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 160.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 60.0, 'g', 0.017552, 1.0531, 0 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 60.0, 'g', 0.0176, 1.056, 1 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 2 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶（ml）', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 180.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '茉莉舂柠檬少少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '紫米（g）', '紫米（半成品）', NULL, NULL, 'WP0530', 60.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '酸奶紫米露';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰勃朗（ml)', '冰勃朗', 'cmpdj8km501r63pmixhitwdzs', 'WP0378', NULL, 20.0, 'ml', 0.0225, 0.45, 1 FROM cost_card WHERE card_name_full = '酸奶紫米露';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '酸奶（g)', '乍甸酸奶', 'cmpdj8kl201qr3pmix7x4o40w', 'WP0383', NULL, 150.0, 'g', 0.01366667, 2.05, 2 FROM cost_card WHERE card_name_full = '酸奶紫米露';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 3 FROM cost_card WHERE card_name_full = '酸奶紫米露';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '酸奶酱（g)', '酸奶酱', NULL, NULL, 'WP0533', 60.0, 'g', 0.01775, 1.065, 4 FROM cost_card WHERE card_name_full = '酸奶紫米露';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 10.0, 'g', 0.017552, 0.1755, 0 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 20.0, 'g', 0.0176, 0.352, 1 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 10.0, 'g', 0.025, 0.25, 2 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 20.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 2.0, 'g', 0.045, 0.09, 4 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '酸角', '酸角果泥果酱', 'cmpdj8igq00xv3pmi7d642fox', 'WP0733', NULL, 40.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 50.0, 'ml', 0.003824, 0.1912, 6 FROM cost_card WHERE card_name_full = '酸角话梅·版纳正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 10.0, 'g', 0.017552, 0.1755, 0 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 20.0, 'g', 0.0176, 0.352, 1 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆（g）', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 10.0, 'g', 0.025, 0.25, 2 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 20.0, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 2.0, 'g', 0.045, 0.09, 4 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '酸角', '酸角果泥果酱', 'cmpdj8igq00xv3pmi7d642fox', 'WP0733', NULL, 40.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙（ml）', '云边乌龙茶汤', NULL, NULL, 'WP0972', 50.0, 'ml', 0.003824, 0.1912, 6 FROM cost_card WHERE card_name_full = '酸角话梅·版纳少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 10.0, 'g', 0.017552, 0.1755, 0 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 1 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制柚子汁', '预制柚子汁', NULL, NULL, 'WP0969', 120.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '小青橘', '小青橘', NULL, NULL, NULL, 4.5, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶汤', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 120.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制青柚粒', '青柚粒', NULL, NULL, 'WP0970', 30.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '寒天冻', '寒天冻', NULL, NULL, 'WP0535', 30.0, 'g', 0.003499, 0.105, 6 FROM cost_card WHERE card_name_full = '青柚与葡萄柚';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香水柠檬片（g）', '柠檬片', NULL, NULL, 'WP0534', 10.0, 'g', 0.017552, 0.1755, 0 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 1 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制柚子汁', '预制柚子汁', NULL, NULL, 'WP0969', 130.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '小青橘', '小青橘', NULL, NULL, NULL, 4.5, 'g', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉茶汤', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 120.0, 'g', NULL, NULL, 4 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制青柚粒', '青柚粒', NULL, NULL, 'WP0970', 30.0, 'g', NULL, NULL, 5 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '寒天冻', '寒天冻', NULL, NULL, 'WP0535', 30.0, 'g', 0.003499, 0.105, 6 FROM cost_card WHERE card_name_full = '青柚与葡萄柚(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '柠檬叶', '柠檬叶', 'cmq28fb2603xe3pq3cgu4lnxp', 'WP0875', NULL, 1.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制青柚汁', '预制柚子汁', NULL, NULL, 'WP0969', 120.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 2 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 20.0, 'g', 0.023628, 0.47256, 3 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙ml', '云边乌龙茶汤', NULL, NULL, 'WP0972', 60.0, 'g', 0.0045, 0.27, 4 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '柠檬叶', '柠檬叶', 'cmq28fb2603xe3pq3cgu4lnxp', 'WP0875', NULL, 1.0, 'g', NULL, NULL, 0 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '预制青柚汁', '预制柚子汁', NULL, NULL, 'WP0969', 130.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 30.0, 'g', 0.0176, 0.528, 2 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 20.0, 'g', 0.023628, 0.47256, 3 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '云边乌龙ml', '云边乌龙茶汤', NULL, NULL, 'WP0972', 70.0, 'g', 0.00385714, 0.27, 4 FROM cost_card WHERE card_name_full = '青柚乌龙冰茶(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 50.0, 'g', 0.0176, 0.88, 0 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 60.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '白柚', '白柚', NULL, NULL, NULL, 40.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 80.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 4 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香柠檬', '柠檬片', NULL, NULL, 'WP0534', 20.0, 'g', 0.017552, 0.351, 5 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 6.0, 'g', 0.015, 0.09, 6 FROM cost_card WHERE card_name_full = '青柚滇橄榄少冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 45.0, 'g', 0.0176, 0.792, 0 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '橄榄混合汁', '橄榄混合汁', NULL, NULL, 'WP0758', 60.0, 'g', NULL, NULL, 1 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '白柚', '白柚', NULL, NULL, NULL, 40.0, 'g', NULL, NULL, 2 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '茉莉（ml)', '云豪茉莉茶汤', NULL, NULL, 'WP0553', 80.0, 'ml', NULL, NULL, 3 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '水果糖浆', '水果糖浆.', 'cmpdj8kwz01un3pmiskqvm04x', 'WP0337', NULL, 5.0, 'g', 0.025, 0.125, 4 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '香柠檬', '柠檬片', NULL, NULL, 'WP0534', 20.0, 'g', 0.017552, 0.351, 5 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '话梅', '洱宝话梅', 'cmpdj8iky00zj3pmi12hb98lb', 'WP0698', NULL, 6.0, 'g', 0.015, 0.09, 6 FROM cost_card WHERE card_name_full = '青柚滇橄榄正常冰';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 20.0, 'g', 0.0176, 0.352, 0 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml）', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 100.0, 'ml', 0.016, 1.6, 1 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 30.0, 'g', 0.0415, 1.245, 3 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 4 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(正常冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 0 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(温热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml）', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 180.0, 'ml', 0.016, 2.88, 1 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(温热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 20.0, 'g', 0.0415, 0.83, 3 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(温热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 4 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(温热)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 20.0, 'g', 0.0176, 0.352, 0 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml）', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 120.0, 'ml', 0.016, 1.92, 1 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 30.0, 'g', 0.0415, 1.245, 3 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 4 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(少冰)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '冰蔗糖（g）', '冰蔗糖浆（新）', 'cmpdj8kwm01ui3pmia673653j', 'WP0338', NULL, 25.0, 'g', 0.0176, 0.44, 0 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '鲜奶（ml）', '悦鲜活鲜奶', 'cmpdj8kkp01qm3pmifea0r080', 'WP0384', NULL, 180.0, 'ml', 0.016, 2.88, 1 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'RAW', '安佳淡奶油', '安佳淡奶油', 'cmpdj8klr01r13pmike5hg2ce', 'WP0381', NULL, 20.0, 'g', 0.0415, 0.83, 3 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(常温)';
INSERT INTO cost_card_item (card_id, item_type, excel_item_name, material_name, material_id, qm_code, semi_code, quantity, unit, unit_price, amount, sort_no) SELECT id, 'SEMI', '黑糖珍珠（g）', '珍珠', NULL, NULL, 'WP0536', 100.0, 'g', 0.013213, 1.3213, 4 FROM cost_card WHERE card_name_full = '鲜奶黑糖啵啵(常温)';

-- ---------- 核对 B：执行后 ----------
-- B1) 按类型计数（PACK 必须仍是 212）
-- SELECT item_type, COUNT(*) FROM cost_card_item GROUP BY item_type;
-- B2) 不应再有零配方卡（期望 0 行）
-- SELECT p.product_name, k.temp_key FROM cost_card k
-- JOIN cost_product p ON p.id = k.product_id
-- LEFT JOIN cost_card_item i ON i.card_id = k.id AND i.item_type <> 'PACK'
-- WHERE i.id IS NULL;
-- B3) PACK 明细未受影响（期望 total=212, itemized=179, lump=33）
-- SELECT COUNT(*) AS total, SUM(material_id IS NOT NULL) AS itemized,
--        SUM(material_id IS NULL) AS lump FROM cost_card_item WHERE item_type='PACK';

-- ---------- 回滚（回到事故后状态） ----------
-- DELETE i FROM cost_card_item i
-- JOIN cost_card k ON k.id = i.card_id
-- WHERE i.item_type <> 'PACK' AND k.card_name_full IN (
--   '手作米布鲜奶茶(冰)', '手作米布鲜奶茶(去冰/常温)',
--   '手作米布鲜奶茶(少冰)', '手作米布鲜奶茶(热)',
--   '手炒黑糖珍珠(去冰/常温)', '手炒黑糖珍珠(少冰)',
--   '手炒黑糖珍珠(正常冰)', '手炒黑糖珍珠(热)',
--   '新10月黄油红糖(等普洱)正常冰', '新10月黄油红糖(等普洱)温热',
--   '杨枝甘露双倍果肉常温', '杨枝甘露双倍果肉正常冰',
--   '树番茄舂柠檬少冰', '树番茄舂柠檬少少冰',
--   '树番茄舂柠檬正常冰', '树番茄话梅·德宏少冰',
--   '树番茄话梅·德宏正常冰', '清甜芭乐冰茶',
--   '清甜芭乐冰茶少冰', '清甜芭乐果奶',
--   '清甜芭乐果奶少冰', '滇橄榄舂柠檬少冰',
--   '滇橄榄舂柠檬少少冰', '滇橄榄舂柠檬正常冰',
--   '滇红舂柠檬少冰', '滇红舂柠檬少少冰',
--   '滇红舂柠檬正常冰', '牛油果燕麦椰椰',
--   '牛油果碧根果', '牛油果酸奶巴旦木',
--   '玫瑰奶白酒-冰', '玫瑰奶白酒-热(无糖版)',
--   '纸杯白毫茉莉(少冰)', '纸杯白毫茉莉(正常冰)',
--   '纸杯白毫茉莉(温热)', '茉莉奶白常温/去冰',
--   '茉莉奶白正常冰', '茉莉奶白温热',
--   '茉莉舂柠檬少冰', '茉莉舂柠檬少少冰',
--   '茉莉舂柠檬正常冰', '酸奶紫米露',
--   '酸角话梅·版纳少冰', '酸角话梅·版纳正常冰',
--   '青柚与葡萄柚', '青柚与葡萄柚(少冰)',
--   '青柚乌龙冰茶', '青柚乌龙冰茶(少冰)',
--   '青柚滇橄榄少冰', '青柚滇橄榄正常冰',
--   '鲜奶黑糖啵啵(少冰)', '鲜奶黑糖啵啵(常温)',
--   '鲜奶黑糖啵啵(正常冰)', '鲜奶黑糖啵啵(温热)'
-- );
